version: "3.7"
services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local